### ISSUE TITLE
Review of P2P network Proof of Work implementation

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1419] opened 2023-11-25 04:55 UTC
It would be good to get an additional review for the conceptual and implementation-wise correctness of the proof of work system used for the p2p network.
Any dev up for that?

**Comment by namloan** [comment] 2023-11-27 06:36
I'm taking this one.

**Comment by namloan** [comment] 2023-12-06 10:54
@djing-chan there's [a TODO in EquihashProofOfWorkService](https://github.com/bisq-network/bisq2/blob/a50a488db6de480ad52486addde12cf955f843e9/security/src/main/java/bisq/security/pow/EquihashProofOfWorkService.java#L30)

> // TODO the scaling of the difficulty does not provide the expected results

Is there any data / experiment you can share that made you reach this conclusion? I assume we'd like to move from Hashcash to Equicash as soon as we get this resolved.

**Comment by HenrikJannsen** [comment] 2023-12-07 12:28
I tested with different difficulties to find out what would be a good value and saw that the changes of difficulty was not reflected in the required work (e.g. ms / xxx hashes). It was not a linear behaviour as its in HashCash and weird jumps. I don't have the data anymore but writing a small iteration with diff. settings and log the results should be easy. 
Maybe it was some local issue on my side or some mistake, but with HashCash all worked as expected. I repeated a few times as I doubted that there is a problem.

Once we have launched changing the PoW algo is tricky. Atm there is no support for multiple pow or for changes.
So would be good to either figure out before launch if Equihash can be used or to add some support for change (not trivial) or accept that HashCash will be used.

**Comment by HenrikJannsen** [comment] 2023-12-15 08:20
Any update on that issue?

**Comment by namloan** [comment] 2023-12-16 07:14
Still working on this. Mainly I've been:
* Reading the [Equihash paper](https://eprint.iacr.org/2015/946.pdf).
* Performing different experiments with multiple seeds to check how difficulty is scaling with the current implementation (Hashcash). Not entirely convinced that this is working as it should; I think I've seen some large differences from the expected PoW that didn't get resolved after all seeds synced up (or at least, not as fast as I'd expect) but I need to keep digging.
* Reviewing [Tor POW implementation](https://github.com/torproject/torspec/blob/main/proposals/327-pow-over-intro.txt) to understand the differences with ours. So I may end up also contributing to https://github.com/bisq-network/bisq2/issues/1147. One of the main differences I've noticed is that they queue the requests by PoW provided, so that requests providing higher PoW get priority.
* Reviewing our choices of cost factors and the difficulty scaling formula. Built a table with all the cost factors to help me see the high level picture:

| Message Type/Category | Cost Factor |
|-----------------------|-------------|
| BondedRoleRegistrationRequest | Bounded between 0.5 and 1 |
| AddAppendOnlyDataRequest, AuthorizeAccountAgeRequest, AuthorizeSignedWitnessRequest, AuthorizeTimestampRequest | Bounded between 0.5 and 1 |
| AuthorizedBondedRole, AuthorizedMarketplaceData, AuthorizedMarketplacePriceData, AuthorizedOracleNode, ReleaseNotification, BannedUserProfileData, AuthorizedAlertData, AuthorizedAccountAgeData, AuthorizedProofOfBurnData, AuthorizedSignedWitnessData, AuthorizedTimestamp Data | 0.5 |
| AddAuthenticatedDataRequest | Bounded between 0.25 and 0.75 |
| ConfidentialMessage | Bounded between 0.1 and 1 |
| AddMailboxRequest | Bounded between 0.25 and 1 |
| MediationRequest, ReportToModeratorMessage | Bounded between 0.25 and 0.5 |
| PrivateChatMessage (Various Specific Types) | Bounded between 0.1 and 0.3 |
| BisqEasyOfferbookMessage, CommonPublicChatMessage, OfferMessage, UserProfile | 0.3 |
| InventoryRequest | 0.25 |
| AckMessage | Bounded between 0.05 and 0.1 |
| PeerExchangeRequest, PeerExchangeResponse | 0.1 |
| Inventory Response | 0.1 |
| MediationResponse | Bounded between 0.1 and 0.2 |
| ConfidentialData | `cipherText.length / 20000` |
| CloseConnectionMessage | 0.05 |
| ConnectionHandshake.Request, ConnectionHandshake.Response | 0.05 |
| Ping, Pong | 0.05 |
| NetworkLoadExchangeRequest, NetworkLoadExchangeResponse | 0.05 |
| AddressValidationRequest, AddressValidation Response | 0.05 |

**Comment by HenrikJannsen** [comment] 2023-12-16 08:41
@namloan Thanks for the feedback. Can you add a comment to https://github.com/bisq-network/bisq2/issues/1147 so that I can assign you?

**Comment by namloan** [comment] 2023-12-25 12:16
@djing-chan are you working on re-enabling [the network load update](https://github.com/bisq-network/bisq2/blob/0d05a7e74ab081f7a353d2854511398769db42a6/network/network/src/main/java/bisq/network/p2p/services/monitor/MonitorService.java#L78)?

**Comment by djing-chan** [comment] 2023-12-27 10:51
@namloan Thanks for reminding me on it. Will re-activate it.

**Comment by djing-chan** [comment] 2023-12-27 11:30
@namloan Fixed here: https://github.com/bisq-network/bisq2/pull/1554
Includes some refactoring..

**Comment by HenrikJannsen** [comment] 2024-01-04 08:45
@namloan What is the state of that issue?

**Comment by namloan** [comment] 2024-01-05 10:22
@HenrikJannsen apologies, I should have updated sooner. I've made very small changes locally to our Equihash to make it exactly the same as the Bisq1 implementation + imported its tests from Bisq1 as well which have some useful benchmarks. Performed a small experiment to visualize the scaling of the difficulty under a constant flow of messages to the offerbook + the de-scaling when it stops. Currently analyzing logs, will update by the end of this week.

**Comment by namloan** [comment] 2024-01-10 00:05
### Summary

I could see that Equihash isn't behaving as expected - possibly due to its difficulty scaling factor (currently ```3e-5```) being too low. As it can be seen in the last graph below (*Equihash - Difficulty vs Adjusted Difficulty*), all difficulty values < 50k ended up being downscaled to 1.0, so no increment in the duration is noticed and even for 50k+ the increment in duration is not that much.

The scaling factor ```3e-5``` was chosen in Bisq1 to *"make the average Hashcash & Equihash puzzle solution times roughly
equal for any given log-difficulty/numLeadingZeros integer"* according to [this commit](https://github.com/bisq-network/bisq/commit/266a7ccea456cf3cee3b7f67700be4414e08cc19) by @stejbac.

1. Need to think more on the right approach here. Does re-evaluating the Equihash difficulty scaling factor / formula make sense or is this unexpected?
2. Difficulty scales well under load; however it takes an hour to start de-scaling even if there is no activity. Is this too much?

Here's the raw analysis:

### Test setup
One seed node, one desktop node, same local machine. Clearnet.

Manually send very short messages to the offerbook at a human rate, maybe 2-3 messages per second for 10 minutes. Then let the application run for 1h+ doing nothing.

Did one using Hashcash, one using Equihash. Both starting from completely cleaned up environments.

Mainly looked at:

* Evolution of the expected difficulty over time, taken from the calculated difficulty when verifying a PeerExchangeRequest / PeerExchangeResponse message. This should provide a good view on whether the raw difficulty value is properly scaling and de-scaling, independently of the PoW algorithm used. It also helps visualize how the experiments were performed.

* The relationship between the actual effort spent in the PoW (duration) and the difficulty. The expectation is the higher the difficulty, the longer the duration.

### Hashcash



![Screenshot 2024-01-09 at 23 25 04](https://github.com/bisq-network/bisq2/assets/138292162/9b2207d2-21fa-46ef-bc31-ffe635d5dcb5)


![Screenshot 2024-01-09 at 23 22 59](https://github.com/bisq-network/bisq2/assets/138292162/ef372571-a2fb-49ed-bbce-f520e2e06abe)

### Equihash

![Screenshot 2024-01-09 at 23 37 10](https://github.com/bisq-network/bisq2/assets/138292162/253572ce-0e2d-4460-ba0e-36a21552c6b1)

![Screenshot 2024-01-09 at 23 38 03](https://github.com/bisq-network/bisq2/assets/138292162/e4587766-424d-4a02-8816-b0486d644b86)

![Screenshot 2024-01-09 at 23 39 10](https://github.com/bisq-network/bisq2/assets/138292162/797f1967-2252-4de9-bc8e-3bb34c89dc20)

**Comment by namloan** [comment] 2024-01-10 08:00
Something that may not be immediately clear from the analysis above - during the experiment, the expected difficulty (minimum difficulty to get a message accepted) of PeerMessageRequests / Responses scaled from ~7000 up to ~30000. This is what the first graph on each experiment represents. I chose PeerMessages to visualize this as the cost factor is very low. The ~50k+ datapoints are exclusively generated by sending messages to the chat - as the minimum difficulty that the sender needs to use starts in ~50k because the cost factor is high.

That's there is a gap in the duration graphs from 30k to 50k - we just didn't generate anything that would fall in the middle, only things with low cost factors (0.05 - 0.1) that happen periodically like PeerExchangeRequests, LoadExchangeRequests, etc or sending messages to the chat with cost factor 0.75.

**Comment by HenrikJannsen** [comment] 2024-01-10 16:48
Great thanks for the investigation and analysis. Do you have also charts of average durations? Is the 50k difficulty for Chatmessages without a high node load? Whats the range of that in high load mode? We might need to adjust the cost factor if the difficulty gets too high in normal mode. 

Do you have any suggestions to change load factors for certain messages?

@https://github.com/stejbac Do you have any idea why the relation of difficulty and duration for creating the pow when using Equihash is not as expected?

We plan to launch in February and changing the pow algorithm later would be difficult. We could add some data to support multiple pow algorithms, but I would prefer to keep things simple.

**Comment by namloan** [comment] 2024-01-11 09:10
> Do you have also charts of average durations?

This should be easy, will share as soon as I plot it

>  Is the 50k difficulty for Chatmessages without a high node load? Whats the range of that in high load mode?

Yes. Difficulty range was 49897 (loadValue=0.01) - 60557 (loadValue=0.174). The question would be whether we consider a load value of 0.174 is 'high load'.

> Do you have any suggestions to change load factors for certain messages?

I avoided jumping to conclusions too fast, just wanted to share the raw analysis to get some feedback especially around the Equihash issue. I'll be doing further analysis. My early thoughts are that cost factors are actually well thought and follow an expected pattern. I see potential tweaks on other areas like the calculation of the load value.

> support multiple algorithms so we can upgrade later

I actually was already looking a bit into this. A simple versioning system like in Bisq1 may do the job, I think Tor does something similar as well. Will take a closer look into this, but a first sight it doesn't look like a blocker for launch to me as we can still implement the versioning later assuming that if an algorithm isn't versioned then it means it's the v0.

**Comment by HenrikJannsen** [comment] 2024-01-11 18:19
Yes the node load calculation from the connection metrics need more work. Its just a rough guestimate. We would also need a more realistic network size to get better data. It also can be that there are some bugs. When I looked at spend time numbers they looked too low to me, but have not looked closer... but could be a bug. Maybe a review of the code already reveal it.
Good is that we can adjust the node load calculation without breaking anything. So best to start carefully and then go up a bit once we have a more realistic network. We will not get ddos'ed but to strict behaviour of the pow system might cause problems. So better to be on the safe side...

**Comment by HenrikJannsen** [comment] 2024-01-11 18:20
Also, have you seen log with warnings about not matching difficulty again? There have been issues earlier but they should be fixed. But not sure as the monitor code was deactivated for a while.

**Comment by namloan** [comment] 2024-01-12 08:28
> Also, have you seen log with warnings about not matching difficulty again

Deviations still happen. Example from the Hashcash experiment:

```
Jan-07 10:49:39.052 [NetworkService.dispatcher-0] INFO  b.n.p.n.a.AuthorizationService: Difficulty of current network load deviates from the proofOfWork difficulty but is inside the tolerated range.
deviationToTolerance=24.66%; deviationToExpectedDifficulty=49.28%; expectedDifficulty=25017.641839274664; proofOfWorkDifficulty=12687.836053504; DIFFICULTY_TOLERANCE=50000
```

I think these happen when one node has already updated its load value and the other didn't yet - these periods can be seen in the jumps of the expected difficulty graphs. Maybe we could think on speeding up the update of the difficulty if we detect a high increase in the load of any of the nodes.

The ones that had been identified as a bug in https://github.com/bisq-network/bisq2/issues/1415 were these ones:

```
Jan-05 08:48:42.096 [NetworkService.dispatcher-0] WARN  b.n.p.n.a.AuthorizationService: Unexpected high difficulty provided. This might be a bug (but valid as provided difficulty is larger as expected): expectedPreviousDifficulty=8799.958990848001; proofOfWorkDifficulty=8800.065923754668 
```

I have 16 instances of these in the Equihash experiment and none in the Hashcash experiment. The deviations are always tiny, the look more like rounding errors somewhere.

**Comment by HenrikJannsen** [comment] 2024-01-12 12:03
Yes we use the previous difficulty to deal with the potentially updated one. But maybe we should look for a more robust method. Any idea?

**Comment by stejbac** [comment] 2024-01-13 14:05
It's a while since I wrote the Java implementation of Equihash, but I believe the scale factor of `3e-5` was arrived at through some rough benchmarking on my own machine (Core i3 CPU M 330 @ 2.13GHz) of Equihash vs Hashcash, which are very different algorithms, so it may not be very accurate and could vary somewhat from one CPU to another. Also, there's some parallelism in the Equihash code, namely during the computation of all the Blake2b hashes to populate the first table when running Wagner's algorithm (which it spends about half its time doing), so the exact scale factor likely depends on the number of CPU cores.

I think one issue you're having is that each Equihash-90-5 puzzle takes about 100ms (or maybe just a few 10's of ms on faster machines) to attempt to solve. The adjusted difficulty is ~0.865 (_1 - e<sup>-2</sup>_) divided by the likelihood that the solution is valid (assuming a Poisson distribution of solutions for each puzzle solution attempt, with mean 2). No matter how low the intended difficultly, there must always be at least one attempt to solve the Equihash puzzle (with probability of success at most 0.865), so there is a floor in the expected time to perform the PoW, seen at difficulty around 30000. For much higher difficulty, the likelihood of any given solution attempt being successful is much lower, so many attempts will be made to solve the puzzle with different nonces and the expected time to perform the PoW will then scale linearly with difficulty as intended.

I chose Equihash-90-5 (_n_=90, _k_=5) for the Bisq 1 BSQ swap DoS protection, as it seemed a good balance of reasonable memory hardness (5-10 MB peak memory usage) and ability to scale difficulty downwards before hitting a floor at around 30000. But there are other choices of _n_ and _k_ that one could make for greater or lesser peak memory usage or minimum achievable difficulty. As commented in the unit tests of Equihash (included in Bisq 1), I benchmarked Equihash-60-4, Equihash-70-4, Equihash-90-5 and Equihash-96-5. Some of those may be more suitable for very low difficulty PoW -- I can't remember exactly how the peak memory usage or puzzle solution times compare with Equihash-90-5, but there are only a rather limited number of valid choices of _n_ and _k_ if I recall correctly.

If you intend a wide range of difficulties starting at a very low value, it would probably be a good idea to dynamically select the choice of _n_ and _k_, each choice with a different difficulty scale factor arrived at experimentally.

**Comment by HenrikJannsen** [comment] 2024-01-13 19:52
Thanks a lot for the inputs @stejbac !

As we would like to release soon (February) I think to get the right settings and test it sufficiently on different CPUs might take too long. 
I would prefer then to postpone the usage of Equihash and start with Hashcash but to add support for selecting the algorithm, so that we can switch later to Equihash once that is sufficiently tuned. @namloan Could you have a look into the best/easiest option for making the algorithm customizable? To not allow a potential attacker (who might use asics for getting an advantage) to abuse the choice, we should have some cutoff date for the old algo once we change.

**Comment by namloan** [comment] 2024-01-14 10:52
> @namloan Could you have a look into the best/easiest option for making the algorithm customizable?

Will do.

> Do you have also charts of average durations?

Here are the plots with the 1-min averages (Hashcash):

![image](https://github.com/bisq-network/bisq2/assets/138292162/7ef96aba-7934-4f3f-a60f-0088bb5bc119)

![image](https://github.com/bisq-network/bisq2/assets/138292162/bd3a7662-d658-4011-9074-3c83ce870edf)

**Comment by HenrikJannsen** [comment] 2024-01-14 17:54
Those numbers have been high load situation, right? Which CPU/OS?

**Comment by namloan** [comment] 2024-01-15 08:33
Apple M2 Pro, OS X Ventura 13.4.1

High load only happened for the first 10 minutes - after that the app remained idle. Notice that the last AddAuthenticatedDataRequest (i.e, message sent to the chat) happened before 11am while the last PeerExchange was one hour later.

**Comment by namloan** [comment] 2024-01-15 08:50
Load values over time:  

![image](https://github.com/bisq-network/bisq2/assets/138292162/7a9413cf-e8fc-46d9-a240-5039802a429b)

**Comment by namloan** [comment] 2024-01-17 09:03
@HenrikJannsen how do you envision the PoW algo selection parameter? would this be a param that can be voted in a DAO proposal? would a bonded role be able to just change it? would appreciate if you could provide some context about how this is currently working in Bisq1.

**Comment by HenrikJannsen** [comment] 2024-01-17 18:15
The easiest option would be to do it hard coded with a release and have an activation date until which all users need to update.
Another option would be to add it as feature to the security manager. The security manager is a DAO bonded role and they could set the option and by that all in the network use that option (can be more then just the algorithm, like some params for the difficulty). That way if we made mistakes with the tuning we could react and fix it on the fly as well react in case of a real attack and if we have been to soft with the params.
I guess option 2 is better and adds more benefits. Downside is that the security manager gets more power and we want to keep the power of those roles to the minimum. But a anyone can ignore the security manager by a flag the risk of abuse is limited (ignoring does not help you if the peer has not ignored it - so that is only for real abuse or if the security manager gets hacked).

**Comment by djing-chan** [comment] 2024-01-18 22:49
Just stumbled over https://spec.torproject.org/hspow-spec/v1-equix.html and https://github.com/tevador/equix
Maybe it is useful when dealing with our EquiHash implementation (e.g there are benchmarks https://github.com/tevador/equix/blob/master/src/bench.c)

**Comment by HenrikJannsen** [comment] 2024-01-24 03:53
I think we should aim for a similar solution as here: https://github.com/bisq-network/bisq2/pull/1626

@namloan Can you work on that? It need to be done for the release (in 1-2 weeks is deadline)

**Comment by namloan** [comment] 2024-01-24 05:19
@HenrikJannsen yes, we have an analysis and clear next steps, so we can close this one.

**Closed** 2024-01-24 12:42 UTC
Labels: p2p
