### ISSUE TITLE
Bug when attempting to Trade

### ISSUE THREAD

**Issue by Ottiz** [bisq-network/bisq2#1849] opened 2024-03-18 03:59 UTC
When I attempted to start an Easy Trade, encountered an error message: the Peers trade failed, illegal argument exception

[bisq.log](https://github.com/bisq-network/bisq2/files/14630699/bisq.log)

**Comment by Ottiz** [comment] 2024-03-18 17:21
![Sending message failed](https://github.com/bisq-network/bisq2/assets/42776992/aafa465e-75d8-44a7-9bf1-d0a5d7a176a0)
screenshot of another trade error

**Comment by HenrikJannsen** [comment] 2024-03-22 15:55
If the exception was caused by that `BisqEasyTakeOfferRequestHandler.validateAmount(BisqEasyTakeOfferRequestHandler.java:140)` it is resolved with https://github.com/bisq-network/bisq2/pull/1895

The message issues are addressed by https://github.com/bisq-network/bisq2/pull/1873 but might be it requires more. We are still investigating.

I close that as its handled by other issues.

**Closed by HenrikJannsen** 2024-03-22 15:55 UTC
