### ISSUE TITLE
Improve management of failed to send private messages

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#1891] opened 2024-03-22 11:04 UTC
I sent a test private message to brokenmoney, and it reported a failure with a red badge containing an exclamation mark, near a clicable to copy the contents of the message, but a button to "retry sending" was missing.
In the meantime, brokenmoney, who was notified via matrix, had sent me a private message, so the notification badge near discussions reported a `(1)`, I clicked on discussions and then on private chats, and my failed message had disappeared, while the received messages by brokenmoney were in the window.

A user will probably expect to see a small button to retry sending the message, and that the failed message is not lost when the other user messages back

**Comment by HenrikJannsen** [comment] 2024-03-28 07:11
I have seen that myself with 2.0.1 but I hope that is fixed by the many bugfixes in 2.0.2. I will try to reproduce it. Note that both traders need to have been updated to be sure its not caused by older bugs.

**Closed** 2024-04-09 06:37 UTC
Labels: network, priority, investigation
