### ISSUE TITLE
trade failed with an error caused by IllegalArgumentException, FsmException

### ISSUE THREAD

**Issue by jomz** [bisq-network/bisq2#1879] opened 2024-03-20 22:21 UTC
Probable duplicate:
https://github.com/bisq-network/bisq2/issues/1871
Just following orders.. (to please open a new issue on GH)
Paste:

The peer's trade failed due an error.
Error caused by: IllegalArgumentException, FsmException

Stack trace: java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.validateAmount(BisqEasyTakeOfferRequestHandler.java:141)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.verifyMessage(BisqEasyTakeOfferRequestHandler.java:105)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.handle(BisqEasyTakeOfferRequestHa...

**Comment by bronco1** [comment] 2024-03-22 12:18
I also had this error.

The peer's trade failed due an error.
Error caused by: IllegalArgumentException, FsmException

Stack trace: java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyBtcAddressMessageHandler.verifyMessage(BisqEasyBtcAddressMessageHandler.java:51)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyBtcAddressMessageHandler.handle(BisqEasyBtcAddressMessageHandler.java:40)
    at bisq.common.fsm.Fsm.handle(Fsm.java:83)
    at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyP...
[BisqEasyTrade_efd167a3.csv](https://github.com/bisq-network/bisq2/files/14722414/BisqEasyTrade_efd167a3.csv)

**Comment by HenrikJannsen** [comment] 2024-03-22 15:00
@bronco1 
It failed because the address was longer then 100 characters. Which address did you use? a LN invoice?
I will relax that check to allow more flexibility.

**Comment by HenrikJannsen** [comment] 2024-03-22 15:14
@jomz 
https://github.com/bisq-network/bisq2/issues/1871  was another issue and I just looked into it and closed it.

Yours failed at
`checkArgument(takersAmount <= maxAmountWithTolerance, errorMsg);`

That happens if the 2 traders price used for calculating the btc amount was more than 1% different.
Which currency did you use? 

It is hard to set here the right value, as if it is too low we get more such errors, if its too large users could abuse it to scam the peer by manipulating the price up to that limit.

I fear the 1% might be too tight and will increase it to 3%.

**Comment by HenrikJannsen** [comment] 2024-03-22 15:16
I close as both cases are addressed in new PRs

**Closed by HenrikJannsen** 2024-03-22 15:16 UTC
Labels: priority

**Comment by bronco1** [comment] 2024-03-22 17:14
> @bronco1 
> It failed because the address was longer then 100 characters. Which address did you use? a LN invoice?
> I will relax that check to allow more flexibility.
> Fixed in https://github.com/bisq-network/bisq2/pull/1893

Yes, it was a lightning invoice

**Comment by HenrikJannsen** [comment] 2024-03-23 04:49
> > @bronco1
> > It failed because the address was longer then 100 characters. Which address did you use? a LN invoice?
> > I will relax that check to allow more flexibility.
> > Fixed in #1893
> 
> Yes, it was a lightning invoice

Thanks that explains it. In 2.0.2 you will be able to use that. Now you could just share the invoice in the chat to the peer
