### ISSUE TITLE
Issues with `BisqEasyOpenTradeMessage`s

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#2395] opened 2024-07-11 08:01 UTC
Issues with `BisqEasyOpenTradeMessage`s when testing main branch with async communication.

* I am sometimes getting duplicated messages.
* When taking an offer, I have seen the following:
    * Not receiving any message at all (not even take offer log message)
![image](https://github.com/user-attachments/assets/34713304-8e34-4fc5-bd95-815923425efd)

    * Only receiving *some* messages (in the screenshot, I sent the sequence test1, test2, test3 but test2 is missing)
![image](https://github.com/user-attachments/assets/2a74a25a-c4d7-4f10-90cb-4af3915e853c)

* I have also gotten a few times already a ghost notification that can't be dismissed either closing the panel or using the button in settings.
![image](https://github.com/user-attachments/assets/a3f5fb8e-e2f3-4cb1-82db-333b12d0bbe0)

**Comment by HenrikJannsen** [comment] 2024-07-26 08:38
Can you reproduce those issues with current version?

**Comment by HenrikJannsen** [comment] 2024-08-10 03:24
There is an open issue with the chat not initialized when deleting a trade and the next gets selected. I will work on that. The rest should be fixed by various bugfixes in that area.

**Comment by HenrikJannsen** [comment] 2024-08-10 03:36
Cannot reproduce it anymore. 
The other mentioned issues should be fixed as well. Could not see any of those issues while testing.

**Closed by HenrikJannsen** 2024-08-10 03:36 UTC
